[project]
name = "qwen-0-6b-quantized"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.3",
    "httpx>=0.27.0",
    "loguru>=0.7.3",
    "tenacity>=9.1.2",
]
